name: main

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scss_css:
    name: Compile SCSS on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node: [10]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install npm dependencies
      run: npm ci

    - name: Run CSS
      run: npm run css
