name: SCSS
on:
  push:
    paths:
      - "scss/**"
  pull_request:
    paths:
      - "scss/**"
env:
  CI: true
  NODE: 10.x

jobs:
  createcss:
    runs-on: ubuntu-latest


    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Build CSS
        run: npm run css

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "Automation: SCSS->CSS"
          branch: ${{ github.head_ref }}
          file_pattern: /home/runner/work/crystalcss/crystalcss/build/css/