name: SCSS
on: [push, pull_request]
env:
  CI: true
  NODE: 10.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - run: node --version
      - run: npm --version
          
      - name: Install npm dependencies
        run: npm ci

      - name: Build CSS
        run: npm run css
      
      - name: push
        uses: github-actions-x/commit@v2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          files: build/css/\*css
          commit-message: 'Auto: Compiled SCSS to CSS'
          rebase: 'true' # pull abd rebase before commit
